apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: familytasks-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: familytasks-dev
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432