name: Terraform Infrastructure CI/CD

on:
  pull_request:
    branches: [ main ]
    paths:
      - "day-27 - Production Infra/**"
      - ".github/workflows/terraform.yml"

  push:
    branches: [ main ]
    paths:
      - "day-27 - Production Infra/**"
      - ".github/workflows/terraform.yml"

  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.11.4

jobs:
  terraform:
    name: Terraform CI/CD
    runs-on: ubuntu-latest

    environment: Prod

    defaults:
      run:
        working-directory: day-27 - Production Infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Terraform apply on main push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

      - name: Run deployment validation script
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: chmod +x scripts/validate.sh && ./scripts/validate.sh

      - name: Manual apply
        if: github.event_name == 'workflow_dispatch' && inputs.action == 'apply'
        run: terraform apply -auto-approve tfplan

      - name: Manual destroy
        if: github.event_name == 'workflow_dispatch' && inputs.action == 'destroy'
        run: terraform destroy -auto-approve